### ISSUE TITLE
[Testing] Spring Testing Trial

### ISSUE THREAD

**Issue by FullSol** [FullSol/amplifier#17]
Resource from Azhya: 
[Spring Boot Testing Basics: How to Unit Test & Integration Test REST Controllers](https://www.youtube.com/watch?v=pNiRNRgi5Ws)

Additional Resources:
[Test Driven Development with Spring Boot - Sannidhi Jalukar, Madhura Bhave](https://www.youtube.com/watch?v=s9vt6UJiHg4)

**Comment by pyaeger** [comment]
What is the scope of this job? I'm interested but need to know more about what you need to see in order to handle this issue properly.

**Comment by FullSol** [comment]
Find documentation, guides, or any resource to learn how to test in spring.

**Comment by pyaeger** [comment]
Okay thanks for clarification. I think @briiitelord expressed interest in testing. I'll hold off on adopting this issue. ☺️

**Comment by FullSol** [comment]
We all need to know each aspect of it, so if you want to jump in as well, feel free!

**Comment by pyaeger** [comment]
True true. Okay then I'm in! I've added myself to this issue. 👍

**Comment by briiitelord** [comment]
Happy to contribute any resources I find, as well as applicable testing tutorials
