### ISSUE TITLE
Presentation Order and Breakdown

### ISSUE THREAD

**Issue by L3viathon** [FullSol/amplifier#240]
# DIABLO III FANSITE 

###### Presentation duration: 30 minutes

1. Team Amplifier Introductions & Roles - Everyone
2. Project Description
3. Tech Stack - Joachim
4. CI/CD - Levi
5. Database Connectivity *(ERD: Needed to CRUD: needed to save user, Battlenet account to hook into Blizzard API, roles to block out specific actions -> Created 5 tables)* - Patrick
6. API Documentation - Patrick
7. BackEnd (JWT) - Calvin and Levi (*code that was fun/interesting/challenging for you*)
8. Postman - Levi and Calvin (*Calvin: User JWT, Roles, SocialMedia | Levi: ImgPost, ImgPostComment*)
9. Testing Backend - Joachim
10. Frontend (*src code highlights*) - Julian
11. Testing Frontend - Joachim
12. FrontEnd demo - Julian
13. Challenges - Everyone
14. (Potentially) Lessons Learned/What went well - Everyone

**Comment by L3viathon** [comment]
@jularmerme @FullSol @briiitelord @pyaeger I will break this down and send it to everyone!

**Comment by pyaeger** [comment]
Thank you! Appreciate it.
